package com.wangbin.clouddemo

case class O_CR_IND_INFO
(
  CustomerID: String, //	客户编号
  HIS_BEGIN_DATE: String,//todo 添加字段
  HIS_END_DATE: String,//todo 添加字段
  FullName: String, //	全名
  Sex: String, //	性别
  Birthday: String, //	生日
  CertType: String, //	证件类型
  CertID: String, //	证件号码
  SINO: String, //	社会保险号
  Country: String, //	国籍
  Nationality: String, //	民族
  NativePlace: String, //	籍贯
  PoliticalFace: String, //	政治面貌
  Marriage: String, //	婚姻状况
  RelativeType: String, //	联系方式
  FamilyAdd: String, //	家庭住址
  FamilyZip: String, //	邮编
  EmailAdd: String, //	电子邮件地址
  FamilyTel: String, //	住宅电话
  MobileTelephone: String, //	移动电话
  UnitKind: String, //	单位性质/所属行业
  WorkCorp: String, //	工作单位
  WorkAdd: String, //	工作地址
  WorkTel: String, //	工作电话
  Occupation: String, //	职业
  Position: String, //	职位
  EmployRecord: String, //	工作履历
  EduRecord: String, //	教育履历
  EduExperience: String, //	最高学历
  Edudegree: String, //	学位
  GraduateYear: String, //	毕业年份
  FinanceBelong: String, //	财务报表所属
  CreditLevel: String, //	本行评估即期信用等级
  EvaluateDate: String, //	本行评估日期
  BalanceSheet: String, //	个人资产与负债详情
  Intro: String, //	个人情况简介
  SelfMonthIncome: String, //	个人月入
  FamilyMonthIncome: String, //	家庭月入
  IncomeSource: String, //	主要收入来源
  Population: String, //	家庭人数
  LoanCardNO: String, //	贷款卡号
  LoanCardinsYear: String, //	贷款卡最新年审年份
  FarmerSort: String, //	农户分类
  Regionalism: String, //	所属行政区域
  Staff: String, //	是否是本行员工
  CreditFarmer: String, //	是否信用用户
  Riskinclination: String, //	风险偏好
  Character: String, //	性格爱好
  DataQuality: String, //	数据质量检查标志
  InputOrgID: String, //	录入机构
  InputUserID: String, //	录入人
  InputDate: String, //	录入日期
  UpdateDate: String, //	更新日期
  Remark: String, //	备注
  UpdateOrgID: String, //	更新机构
  UpdateUserID: String, //	更新人
  CommAdd: String, //	通讯地址
  CommZip: String, //	通讯邮编
  NativeAdd: String, //	户籍地址
  WorkZip: String, //	地址邮编
  HeadShip: String, //	职务
  WorkBeginDate: String, //	本单位工作起始年份
  YearIncome: String, //	年收入
  PayAccount: String, //	工资帐号
  PayAccountBank: String, //	开户银行
  FamilyStatus: String, //	居住状况
  TempSaveFlag: String, //	暂存标志
  Pinyin: String, //	拼音/英文名
  IslocalResident: String, //	是否本地户口
  CertMaturity: String, //	证件到期日
  EmergencyContact: String, //	紧急联系电话（区号+总机）
  MoveInYear: String, //	入住年份
  ConsArea: String, //	建筑面积
  ResidentialStatus: String, //	住宅性质
  EmployerCategory: String, //	单位性质2
  SelfEmployed: String, //	是否自雇
  CountryOfIssuance: String, //	发证国家/地区
  HouseHoldIncome: String, //	家庭年收入（元）
  PreYearDPF: String, //	上年度公积金缴存（元）
  Balance: String, //	剩余贷款本金（元）
  MlBalance: String, //	其中住房贷款
  AlBalance: String, //	汽车贷款（元）
  OtherBalance: String, //	其他贷款（元）
  CclLine: String, //	信用卡额度
  MonthlyRepayment: String, //	没月还款金额（元）
  OtherLiabilities: String, //	其他负债（元）
  OwnOtherProperty: String, //	是否在本市拥有其他房产
  BrandPV: String, //	自有汽车品牌
  PlateOfPV: String, //	自有汽车牌照号
  OtherValuable: String, //	其他重要财产
  Saving: String, //	银行存款及有价证券
  PartnerCustID: String, //	配偶客户代码
  PeopleInHouseHold: String, //	家庭供养人口数
  Ifemltm: String, //	是否供职单位未满一年
  CerttimType: String, //	证件期限类型
  RentbyMonth: String, //	每月租金(元)
  FirstName: String, //	英文姓氏
  SecondName: String, //	英文名
  OwnersShipBeing: String, //	拥有的职务
  FamilyAddArea: String, //	现居住区域
  Age: String, //	年龄
  CompPosition: String, //	企业职位
  ManageYears: String, //	管理年职
  HoldShare: String, //	持股量
  OtherPropertyAdd: String, //	不动产地址
  BhappendInfo001: String, //	担保人与借款企业的关系
  BhappendInfo002: String, //	持有企业股权的比例
  BhappendInfo003: String, //	其他关系请注明
  BhappendInfo004: String, //	担保人与借款企业法定代表人关系
  BhappendInfo005: String, //	其他关系请注明
  WorkYear: String, //	运营年限
  LetCompany: String, //	运营公司名称
  Add1: String, //	运营公司地址
  Zip1: String, //	运营公司邮编
  Phone1: String, //	运营公司电话（区号＋总机＋分机）
  NATIVEPLACE1: String, //	户籍街道
  INDAPPLYTYPE: String, //	申请人类别
  INDAPPLYTYPECERTNUM: String, //	优惠证或退役军人自谋职业证号码
  ISTRAINING: String, //	是否参与培训
  UNTRAINREASON: String, //	未培训原因
  ISAPPLY: String, //	是否失业且已申请小额担保贷款
  RETRIINGAGE: String, //	法定退休年龄
  ACCMONTHAMOUNT: String, //	公积金月缴额
  REACCMONTHAMOUNT: String, //	补充公积金月缴额
  ACCAMOUNT: String, //	公积金余额
  REACCAMOUNT: String, //	补充公积金余额
  WORKCORPACCOUNT: String, //	主贷人单位公积金账号
  INDACCACOUNT: String, //	主贷人个人公积金账号
  SPECIFICDUTY: String, //	具体职务
  HOUSEADDRESS: String, //	房屋座落
  HOUSEAREA: String, //	建筑面积
  ENDDATE: String, //	竣工日期
  CARMODELNO: String, //	车辆型号
  CARMARKNO: String, //	牌照号
  CARBUYTIME: String, //	购入时间
  OfficialFriendly: String, //	是否高管亲属
  IndCategory: String //	借款人性质
)
